### ISSUE TITLE
Small gripe about sys_win.c

### ISSUE THREAD

**Issue by lankymart** [ThijsWouters/handmade_quake#1]
Shouldn't it be `sys_linux.c` due to the fact it's Linux not Windows and also to match the original implementation in [Id Softwares source](https://github.com/id-Software/Quake/blob/master/WinQuake/sys_linux.c)?

**Comment by ThijsWouters** [comment]
That's true. I'll change that.
I haven't looked at the original source. Because I don't want to match it exactly. It is after all 20 years old.
